### ISSUE TITLE
MinuVis reagiert manchmal sehr sehr langsam

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/ioBroker.minuvis#13]
Hallo Sepp,

ich habe heute weiter an meiner Visualisierung gearbeitet. Ich habe in einer Seite mit sechs Outputwidgets und einem iFramewidget die outputwidgets mit dem Compactwidget gruppiert. Da jedes zusätzliche Widget immer am Ende der Seite erstellt wird musste ich diese nach oben schieben und genau dabei hat es immer wieder gehakt und echt lange gedauert, sowohl mit Firefox x64 wie auch mit Edge (beide ganz aktuell). 

Vielleicht besteht ja die Möglichkeit das Erstellen neuer Widgets anders zu gestalten. 

Ich hoffe das ist hier richtig, ich erstelle meine Visualisierung mit dem ioBroker Adapter. 

Gruß Michael

**Comment by SVallant** [comment]
Die Version des Builders steht rechts unten. Sonst ist er gleich.
Es ist gedacht, das Builder und App die gleiche Version haben sollten.

**Comment by SVallant** [comment]
http://dev.builder.minukodu.de/
Neue Version V1.4.0-dev
Sollte jetzt flüssiger gehen ... bitte testen

Das Erstellen von neuen Widgets gucke ich mir an, wie man das machen könnte

**Comment by MMeinhardt1** [comment]
Hi, das klingt ja gut. Ich hatte heute morgen kurz geschaut aber kein Update des minuvis Adapters im ioBroker gesehen. Gilt das nur für die selbstgehostete Variante?

Danke

**Comment by SVallant** [comment]
Nein, die kommt erst nach erfolgreichem dev-Test, werde heute noch andere Sachen updaten, derzeit kann man im dev-Builder schon Filler mit Überschriften machen ;-)

**Comment by SVallant** [comment]
Kannst du bitte mal dem dev-Builder testen ?
http://dev.builder.minukodu.de/
Habe ich komplett überarbeitet und aufgeräumt
Danke
Sepp

**Comment by MMeinhardt1** [comment]
Hi, ich werde das morgen Vormittag testen, vorher habe ich keinen Rechner und auf dem Tablet ist das uncool. Ich melde mich.

**Comment by SVallant** [comment]
ok, aber bitte nicht an einem Produktiv-System, es hat sich viel getan ..
du kannst auch unsere Demo nutzen: http://94.130.57.38:9090

**Comment by MMeinhardt1** [comment]
Der Link funktioniert leider nicht

**Comment by SVallant** [comment]
http://dev.builder.minukodu.de/ ist der Builder, http://94.130.57.38:9090/ die Adresse zum Verbinden mit der IoBroker-DemoSiehe AnhangSepp--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04.09.20, 11:24 schrieb MMeinhardt1 <notifications@github.com>:

   
  Der Link funktioniert leider nicht

**Comment by MMeinhardt1** [comment]
Hallo Sepp,

danke für Deine Antwort, leider hatte ich erst geschrieben und danach erst das Hirn eingeschaltet.

Ich habe das jetzt gerade mal getestet und ich muss sagen das sieht sehr gut.
Die Beschriftung für ein CompactWidget funktioniert grundsätzlich, allerdings wird es in die anderen Widgets hineingeschoben wenn das Wort zu lang ist wenn man es z.B. auf dem Handy nutzt (dies ist meine bevorzugte Nutzungsquelle). Vielleicht läßt es sich ja mit einem Zeilenumbruch realisieren das es dann unter dem Symbol steht. Wenn man dafür ein Filler-Widget nutzt sieht es nicht mehr ganz so hübsch aus.
Die Beschriftung in der Zeile, in der auch Datum und Zeit stehen, fände ich so hoffe ich noch besser, und dafür das Datum hoch zu den "online" Symbol und die Zeiten der States irgendwie mit in die einzelnen Widgets. (Ich versuche das am WE mal grafisch umzusetzen damit Du auch ein Bild zu meinen vielen Worten hast)  

Ansonsten läuft es sehr viel flüssiger als die Vorgängerversion! Auch die neuen Schaltflächen an der rechten Seite sind überaus praktisch, dann braucht man nicht immer scrollen!

Es kommt bestimmt noch mehr. Meine Config ist unter MM gespeichert.

**Comment by MMeinhardt1** [comment]
Ging doch schneller, so ungefähr dachte ich.

![Neu](https://user-images.githubusercontent.com/56205459/92230700-dba40800-eeab-11ea-93bd-4130781409b9.png)
 Das rote @ Uhrzeit gilt für einen States dessen Zeitstempel nicht von aktuelle Tag ist.

**Comment by SVallant** [comment]
valueswitcher hat nun eine neue Eigenschaft "showAsIndicator"; es wird dann nur 1 Icon wie ein Indicator dargestellt (in Abhängigkeit der 4 Werte)

**Comment by MMeinhardt1** [comment]
Moin Moin, die neue Option in den Filler Widgets gefällt mir sehr gut. Allerdings fehlt mir persönlich jetzt die Unterteilung, in ersten Screenshot habe ich das mal eingezeichnet und auf dem zweiten sieht man es noch deutlicher das dort irgendwie was fehlt, so rein optisch. Btw. im Hochformat passt das alles ganz gut, im Querformat müsste man glaube ich ganz schön basteln (das dann mal wenn ich mir eine extra Vis für Tablet baue).

Das Datum hast Du jetzt ganz rausgenommen? Schade.

Bezüglich der Zeitstempel und Deinem Beispiel, was wäre für Dich nicht ok wenn es vorgestern geregnet und der angezeigte Zeitstempel der Regenmenge wäre dann rot? Dadurch würdest Du doch genau sehen können das der Wert nicht von heute ist. Das "Problem" der Zeitspempel tritt ja auch nur dann auf wenn man den Compact Mode nutzt, wenn man einzelne Widgets verwendet wird ja auch der entsprechende Zeitstempel angezeigt. Im Compact Mode eben nur der letzte und dadurch kann man leider nicht erkennen von welchem Widget der kommt.

Ganz wichtig für mich, gibt es die Möglichkeit "kein" Icon auszuwählen?

![1](https://user-images.githubusercontent.com/56205459/92302815-597d1780-ef6f-11ea-8c7d-4497d8db7b18.png)

![2](https://user-images.githubusercontent.com/56205459/92302819-613cbc00-ef6f-11ea-9ef4-7fe2a8f4cc28.png)

**Comment by SVallant** [comment]
ok, das mit der Unterteilung guck ich mir.
Bzgl. Zeitstempel, es gibt auch Werte die ändern sich nur monatlich, diese Zeitstempel sind dann dauernd rot ?
Ich werde erstmal die Zeitstempel weider im enzelnen Widget anzeigen wie du vorgeschlagen hast, erstmal weiss ...dann schauen wir mal

_Ganz wichtig für mich, gibt es die Möglichkeit "kein" Icon auszuwählen?_ => in welchem Widget ?

**Comment by MMeinhardt1** [comment]
> _Ganz wichtig für mich, gibt es die Möglichkeit "kein" Icon auszuwählen?_ => in welchem Widget ?

Auf jeden Fall mal in dem Filler Widget wenn man es als "Überschrift" verwendet. Mehr fällt mir noch nicht ein.

Gibt es die Möglichkeit meine bestehende Vis zu exportieren und mit der neuen Version zu testen? Oder müsste ich alles händisch neu machen?

**Comment by MMeinhardt1** [comment]
> 
> 
> valueswitcher hat nun eine neue Eigenschaft "showAsIndicator"; es wird dann nur 1 Icon wie ein Indicator dargestellt (in Abhängigkeit der 4 Werte)

Wie genau funktioniert das bzw. wofür ist das gedacht? Ich kann hier nur ein Objekt eintragen, ich stehe grad auf dem Schlauch.

**Comment by SVallant** [comment]
bzgl. ValueSwitcher Beispiel:
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate
je 1 Icon für jeden der 4 Zustände, vielleicht später auch noch mit 4 Farben

**Comment by MMeinhardt1** [comment]
> 
> 
> > valueswitcher hat nun eine neue Eigenschaft "showAsIndicator"; es wird dann nur 1 Icon wie ein Indicator dargestellt (in Abhängigkeit der 4 Werte)
> 
> Wie genau funktioniert das bzw. wofür ist das gedacht? Ich kann hier nur ein Objekt eintragen, ich stehe grad auf dem Schlauch.

Ich habe mal genauer geschaut, man könnte es fast z.B. als Visualisierung eines Akkus nehmen.

**Comment by SVallant** [comment]
bzgl. Export
verbinde dich im dev-Builder doch mit deiner IO-Broker-Instanz ...
sollte nichts passieren ;-)
Am besten ein Backup machen. Die Config-Dateien liegen entweder hier:
/opt/iobroker/iobroker-data/files/socketio/minukodu
oder hier:
/opt/iobroker/iobroker-data/files/web/minukodu
je nachdem welche soketio-Instanz du nutzt

**Comment by SVallant** [comment]
> 
> 
> > > valueswitcher hat nun eine neue Eigenschaft "showAsIndicator"; es wird dann nur 1 Icon wie ein Indicator dargestellt (in Abhängigkeit der 4 Werte)
> > 
> > 
> > Wie genau funktioniert das bzw. wofür ist das gedacht? Ich kann hier nur ein Objekt eintragen, ich stehe grad auf dem Schlauch.
> 
> Ich habe mal genauer geschaut, man könnte es fast z.B. als Visualisierung eines Akkus nehmen.

genau wenn man noch Fraben hätte ... ;-)

**Comment by MMeinhardt1** [comment]
> 
> 
> > > > valueswitcher hat nun eine neue Eigenschaft "showAsIndicator"; es wird dann nur 1 Icon wie ein Indicator dargestellt (in Abhängigkeit der 4 Werte)
> > > 
> > > 
> > > Wie genau funktioniert das bzw. wofür ist das gedacht? Ich kann hier nur ein Objekt eintragen, ich stehe grad auf dem Schlauch.
> > 
> > 
> > Ich habe mal genauer geschaut, man könnte es fast z.B. als Visualisierung eines Akkus nehmen.
> 
> genau wenn man noch Farben hätte ... ;-)

Die richtigen Symbole werden dann aber leider nur bei den exakten Werten angezeigt, sonst nicht.

**Comment by MMeinhardt1** [comment]
> 
> 
> bzgl. Export
> verbinde dich im dev-Builder doch mit deiner IO-Broker-Instanz ...
> sollte nichts passieren ;-)
> Am besten ein Backup machen. Die Config-Dateien liegen entweder hier:
> /opt/iobroker/iobroker-data/files/socketio/minukodu
> oder hier:
> /opt/iobroker/iobroker-data/files/web/minukodu
> je nachdem welche soketio-Instanz du nutzt

Funktioniert, leider findet er kein Config-File

**Comment by SVallant** [comment]
er verbindet, findet aber nichts ??? keine States kene Files ?

**Comment by MMeinhardt1** [comment]
States hat er aber leider kein bestehendes config-file

**Comment by SVallant** [comment]
hast sicher den richtigen Port ?

**Comment by SVallant** [comment]
aber In- und Export muss auch auf die Liste ...

**Comment by MMeinhardt1** [comment]
> 
> 
> hast sicher den richtigen Port ?

Natürlich nicht, ich Vollpfosten. Jetzt klappts

**Comment by MMeinhardt1** [comment]
Es klappt.

Egal welches Value ich als maximal im ValueSwitcher eintrage, es bleiben immer 4 Stück. Auch wird der aktuelle State nicht farbig hinterlegt. Ich nutze es für unsere Rollläden.

**Comment by MMeinhardt1** [comment]
Hier würden mir rein optisch die schwarzen balken fehlen, müssen nicht ganz so hoch sein wie vorher und auch das datum müsste nicht sein wenn man es tatsächlich oben unter dem online symbol hat. mecker mecker mecker

![temp](https://user-images.githubusercontent.com/56205459/92307387-577a7f00-ef96-11ea-8b64-321e9246031a.png)

**Comment by MMeinhardt1** [comment]
So sieht es sehr gut aus!
![ja](https://user-images.githubusercontent.com/56205459/92307509-5564f000-ef97-11ea-8733-4e686aa4e0dc.png)

So leider nicht, da fehlt die optische trennung und auch sind zwei icons estwas zu viel.
![nein](https://user-images.githubusercontent.com/56205459/92307525-6dd50a80-ef97-11ea-9397-7012a997f643.png)

**Comment by SVallant** [comment]
> Egal welches Value ich als maximal im ValueSwitcher eintrage, es bleiben immer 4 Stück. Auch wird der aktuelle State nicht farbig hinterlegt. Ich nutze es für unsere Rollläden.

ok, da war noch ein Fehler im Builder nach Reload sollte es jetzt gehen:
so habe ich getestet
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate

**Comment by MMeinhardt1** [comment]
Hi, der ValueSwitcher funktioniert soweit wieder. Allerdings werden die Werte nicht mehr farbig hinterlegt, ist das gewollt? Und es gibt hinter dem Wert der oben angezeigt wird keine Unit mehr, ist das auch so gewollt?

**Comment by MMeinhardt1** [comment]
> 
> 
> > Egal welches Value ich als maximal im ValueSwitcher eintrage, es bleiben immer 4 Stück. Auch wird der aktuelle State nicht farbig hinterlegt. Ich nutze es für unsere Rollläden.
> 
> ok, da war noch ein Fehler im Builder nach Reload sollte es jetzt gehen:
> so habe ich getestet
> http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate

Hallo Sepp,
das Prinzip ist klar und habe verstanden. Wenn man es allerdings so löst ist es ja sehr statisch und zeigt nur bei den exakten Werten auch die angegebenen Icons an. Schön wären Wertebreiche, um z.B. den Füllstand eines Regenwasserspeichers oder von Batterien anzeigen zu können. Möglich wäre es dann sicherlich auch, wenn man einem Regensensor hat die Intensität des Regens darzustellen.

PS. wenn ich programmieren könnte würde ich Dir sehr gerne helfen, doch leider ist mir das nicht gegeben. Schade, deswegen kann ich auch leider nur Wünsche äußern und hoffen das Du die Sinnhaftigkeit für Dich erkennst und es umsetzen magst.

**Comment by SVallant** [comment]
so, **unit** beim ValueSwitcher ist wieder da ;-)
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate
Das bei dir immer 4 Buttons sind kann ich nicht nachvollziehen.
Kannst du mal "save and show config js" machen, dann in der config nach **"type": "valueswitcher"** suchen und dann nach "nbOfButtons" ...
auch value 1..4 sollte passen. UNBEDINGT mit STRG+F5 Reload machen im Browser !

Sepp

**Comment by SVallant** [comment]
ich werde übrigens im Laufe der Woche auch noch dei Möglichkeit eines Titels ohne Icon schaffen "NOICON_" + Titel
und dann am Wochenende den Adapter updaten ;-)

**Comment by MMeinhardt1** [comment]
Hi, der valueswitcher funktioniert so wie er soll, auch mit unterschiedlichen anzahl an buttons. alles gut, das hatte ich aber vorhin auch geschrieben! Habe ich vielleicht nicht gut zitiert. Sry.

> Hallo Sepp,
> das Prinzip ist klar und habe verstanden. Wenn man es allerdings so löst ist es ja sehr statisch und zeigt nur bei den exakten Werten auch die angegebenen Icons an. Schön wären Wertebreiche, um z.B. den Füllstand eines Regenwasserspeichers oder von Batterien anzeigen zu können. Möglich wäre es dann sicherlich auch, wenn man einem Regensensor hat die Intensität des Regens darzustellen.

Was denkst Du darüber?

**Comment by MMeinhardt1** [comment]
> 
> 
> ich werde übrigens im Laufe der Woche auch noch dei Möglichkeit eines Titels ohne Icon schaffen "NOICON_" + Titel
> und dann am Wochenende den Adapter updaten ;-)

**Comment by SVallant** [comment]
so, ich bitte um einen Test:

- Titel ohne Icon; "NOICON_" + Titel
- CompactMode -Titel im Header
- ValueSwitcher-Anzeige bei State-Type: "Number":  (Abwahl durch "highlight button if value matches exactly" möglich
-- value <= 1 : Button 1 bzw, Icon 1
-- value >1 und  <=2: Button 2 bzw, Icon 2
-- value >2 und  <=3: Button 2 bzw, Icon 2
-- value >3 : Button 2 bzw, Icon 2

http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate

**Comment by MMeinhardt1** [comment]
Hallo Sepp,

- kein Icon > funktioniert
- Titel im Header > funktioniert ebenfalls (hat es aber das letzte mal auch schon ?)
- ValueSwitcher-Anzeige > das verstehe ich nicht so ganz

Hast Du an den Widgets wieder etwas geändert? Das sah letzte Woche alles ganz anders aus und auch das hinzufügen neuer Widgets geht nur noch oben? Und war es letzte Woche nicht auch schon V1.4 beim Builder?

Ich stehe leider voll auf dem Schlauch, SRY

**Comment by SVallant** [comment]
Öffnen mal diesen Link http://dev.builder.minukodu.de/ und reload mit STRG+F5 dann bist du aktuell, Widget-mässig geht bei mir alles

bzgl.ValueSwitcher
- wenn Wert ein Typ "Number" ist dann
- Button1 bzw. Icon1 sichtbar/gefüllt wenn Wert <= Wert1
- Button2 bzw. Icon2 sichtbar/gefüllt wenn Wert > Wert1 und <= Wert2
- Button3 bzw. Icon3 sichtbar/gefüllt wenn Wert > Wert2 und <= Wert3
- Button4 bzw. Icon4 sichtbar/gefüllt wenn Wert >= Wert 4

dazu jetzt auch 4 verschiedene Farben im Indicator

AUSSER "hightlightExactValueOnly" ist true

ABER ich seh schon, die Version ist nicht aktuell, werde dies fixen, melde mich dann ...

**Comment by MMeinhardt1** [comment]
Hi,

jetzt ist es die Version 1.4, ich hatte es vorhin aber auch schon mal mit strg+f5 probiert. egal.
Den Indicator mit vier Farben habe ich leider noch nicht entdecken können, ansonsten sieht es sehr gut aus.
Und "AUSSER "hightlightExactValueOnly" ist true" kann ich auch nirgends entdecken.

Danke

**Comment by SVallant** [comment]
ja, ich hatte ne alte Version online ..
nun die aktuelle .. sry

**Comment by MMeinhardt1** [comment]
Das sieht sehr gut aus!
Den ValueSwitcher kann man leider nicht in ein CompactModeWidget "verpacken", bekommst Du das noch hin? Oder falls es doch funktioniert dann zeige mir bitte wie, ich bekomme es nicht hin.

**Comment by SVallant** [comment]
Nein, das geht noch nicht, vielleicht in einer späteren Version.
Ich werde jetzt erstmal eine neue version des Adapters veröffentlichen, dann machen wir weiter ...
Slider und TimePicker wollte ich dann Auch "compactfähig" machen.
ich schliesse jetzt diese Issue.
