### ISSUE TITLE
Update auf Builder 1.7.0

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/ioBroker.minuvis#19]
Hallo Sepp,
hast Du schon nen Plan wann das Update kommen wird?

Danke

**Comment by SVallant** [comment]
nicht wirklich, momentan gibt noch einen Bug mit dem Format des Time- und Date-Widget im Firefox
Brauchst du die json-Formatierung ?
Dann mache ich ein "Zwischenupdate" ;-) bis zum Wochenende ...

**Comment by MMeinhardt1** [comment]
Lebenswichtig ist das nicht, kümmere Dich gerne erstmal um die vorhandenen Probleme und Update es dann gemeinsam. 
Wenn es mir dann doch zu lange dauert melde ich mich wieder 😜

**Comment by SVallant** [comment]
update auf V1.8 nun verfügbar (Adapter V0.0.11)
