### ISSUE TITLE
Value-Switcher nur ganze Zahlen möglich

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/ioBroker.minuvis#20]
Hi Sepp,

mir ist vorhin aufgefallen das ich im Value-Switcher nur ganze Zahlen übergeben kann.
Ich wollte mein Heizkörperthermostat mit 20.5 Grad füttern, das klappt aber nicht er übernimmt nur 20 Grad. Wenn ich den Heizkörperthermostat in den Objekten händisch auf 20.5 Grad einstelle zeigt der Value-Switcher diesen Wert korrekt an. Und es ist ein Punkt, kein Komma!
Kann der Value-Switcher nur ganze Zahlen?

Danke
Michael

**Comment by SVallant** [comment]
Moin Michael,
Ja sieht so aus ... :-|
Ich guck mir das heute Abend mal an, habe schon eine Idee
Sepp

**Comment by MMeinhardt1** [comment]
Das klingt ja gut 😃

**Comment by SVallant** [comment]
teste mal bitte gegen den http://dev.builder.minukodu.de/
ob die anderen Werte noch ok sind ...
Beispiel:
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate

**Comment by MMeinhardt1** [comment]
Hi Sepp,
grundsätzlich funktioniert die Weitergabe der Werte nun, allerdings werden die Werte nicht korrekt über die Icons im ValueSwitcher dargestellt. Ich habe ein kleines gif angehangen das Dir hoffentlich zeigt was ich meine und hilft.

![ValueSwitcher](https://user-images.githubusercontent.com/56205459/98977294-c0432200-2518-11eb-895a-77267799d7ac.gif)

**Comment by SVallant** [comment]
wie steht der Schalter: "fill button if value matches exactly" ??

![grafik](https://user-images.githubusercontent.com/3719598/98982620-f59f3e00-251f-11eb-9198-94063114c380.png)

im Builder geht es ja ...
http://dev.builder.minukodu.de/minuvis/app/?url=http%3A%2F%2F94.130.57.38%3A9090%2F&file=Test_ValueSwitcher.json&forceUpdate

**Comment by SVallant** [comment]
.. und OffTopic: Welche Thermostate verwendest du ? Wie an IOBroker angebunden ?

**Comment by MMeinhardt1** [comment]
Hi Sepp,
"fill button if value matches exactly" war natürlich nicht angeschaltet, habe soeben mit "fill button if value matches exactly" angeschaltet ausprobiert und es hat funktioniert. Dann klappt alles!!

> 
> 
> .. und OffTopic: Welche Thermostate verwendest du ? Wie an IOBroker angebunden ?

Das sind [MOES HY368](https://www.moeshouse.com/products/tuya-zigbee3-0-new-mini-wifi-radiator-actuator-smart-programmable-thermostat-temperature-trv-controller) Heizkörperthermostate, angebunden über Zigbee.
