### ISSUE TITLE
Version problem 1.1.0 npm package

### ISSUE THREAD

**Issue by Apollon77** [minukodu/ioBroker.minuvis#25]
I just upgraded to 1.1.0 and in the installed io-package the verison is still 1.0.0 but news from 1.1.0 ... so it seems that the npm package was published wrong ... so admin always shows an available update. maybe you want to publish a 1.1.1 with a correct io-package?

**Comment by SVallant** [comment]
yes, i hope this weekend ...

**Comment by SVallant** [comment]
published V1.2.0
