### ISSUE TITLE
RequestForComment - Enhancement common.states

### ISSUE THREAD

**Issue by Apollon77** [minukodu/ioBroker.minuvis#70]
Hi @SVallant,

we plan to enhance the definition of common.states  definitoipn as described in https://github.com/ioBroker/ioBroker.docs/pull/387/files

Please provide feedback and also an info if you would support this as adjustment in the adapter in the future.

Thank you

Ingo

**Comment by SVallant** [comment]
Hi Ingo,
good job, i will support it
Sepp

**Comment by Apollon77** [comment]
it is merged in the "docs" ... have fun :-)
