### ISSUE TITLE
2 Instanzen möglich? V1 und V2

### ISSUE THREAD

**Issue by MMeinhardt1** [minukodu/ioBroker.minuvis#77]
Hallo @SVallant,
ich weiß es steht geschrieben das nur eine Instanz möglich ist, gilt das nur innerhalb einer Version oder versionsübergreifend?
Bin bislang noch auf V1 und scheue den Umstieg auf V2 noch etwas wegen der bevorstehenden Arbeit und dem WAF. Wenn beide zeitgleich möglich wären könnte ich in Ruhe mit der V2 rumbasteln bis es passt und stehe nicht so unter Zeitdruck.

Danke und ein schönes Wochenende!

**Comment by MMeinhardt1** [comment]
Hi, das sprengt meine Möglichkeiten. Dann muss ich wohl erst meine Renovierungsarbeiten beenden und auf schlechtes Wetter warten bis ich da ran setzen kann. 🤣

**Comment by SVallant** [comment]
naja, wenn dein ioBroker auf einem Linux-System läuft, hast du den Webserver meistens schon dabei
Was meldet den http://<deine ioBroker-IP>   ??

**Comment by MMeinhardt1** [comment]
ja ein webserver läuft auf dem RPI4, aber ich glaube das ist mir zu viel gebastel.

**Comment by SVallant** [comment]
du musst wirklich "nur" die Dateien da rein kopieren:
meistens in /var/www/html/ 
neue Ordner erstellen minuvis/app
und dann die Minuvis-WebApp (https://github.com/minukodu/minuvis-webapp.iobroker/releases/tag/V1.13.0) dort rein kopieren

**Comment by MMeinhardt1** [comment]
Und dann ne 2te Instanz in V2 installieren? Muss zusätzlich noch etwas konfiguriert werden?

**Comment by SVallant** [comment]
Nein, dann die V1-Version über den WebServer ansteuern:
alte URL der App: 
**http://<ioBroker-Ip>:8082/**minuvis/app/?url=http%3A%2F%2FXX.XX.XX.XX%3A8082&file=XXXX.json&forceUpdate
neue URL: 
**http://<ioBroker-Ip>/**minuvis/app/?url=http%3A%2F%2FXX.XX.XX.XX%3A8082&file=XXXX.json&forceUpdate

damit hast du V1 zweimal und kannst V1 via WebServer weiterbenutzen
Dann in ioBroker V1 updaten auf V2 und V2 konfigurieren
Tipp: Config-Dateien eindeutig als "V2" speichern und NICHT überschreiben

.. und wie immer vorher Backup machen

**Comment by MMeinhardt1** [comment]
Ah ok, dann werde ich das mal testen.
Die V1 könnte ich aber bei Bedarf weiterhin bearbeiten?

**Comment by SVallant** [comment]
wenn du V1 weiter bearbeiten willst, musst du den Builder auch in den WebServer-Ordner kopieren
Ich denke das einfachste wäre, den letzten V1-Adapter https://github.com/minukodu/ioBroker.minuvis/archive/refs/heads/V140.zip runterzuladen, entpacken und den Inhalt des www-Ordners in deinen Webserver in den Ordner var/ww/html/minuvis kopieren, sodass der Builder unter 
http://<**ioBroker-Ip**>/minuvis/builder/
und die App unter
http://<**ioBroker-Ip**>/minuvis/app/
erreichbar ist.
Damit hättest du dann die V1 komplett ausgelagert und könntest den V2-Adapter installieren (wenn bei V1 vom WebServer alles geht)


![grafik](https://user-images.githubusercontent.com/3719598/174426040-5e00bdad-3646-4503-88e2-d5476fadf88a.png)

**Comment by MMeinhardt1** [comment]
Guten Morgen Sepp @SVallant,

das installieren hat soweit gut geklappt und war auch genau die richtige Entscheidung!
Nach Update auf V2 im ioBroker habe ich versucht die Config V1 zu importieren und das hat leider nicht gut geklappt, es kommt nur eine fast leere Seite dabei raus. Habe ich etwas falsch gemacht?
Ich hänge dir mal meine beiden Config´s an, eventuell kannst du ja behilflich sein. Ich habe aus *.json *.txt gemacht da man die Dateien hier sonst nicht hochladen kann.

Vielen Dank und nen schönen Sonntag noch!

[iPad_V1 - Kopie.txt](https://github.com/minukodu/ioBroker.minuvis/files/8986093/iPad_V1.-.Kopie.txt)
[iPad_V2 - Kopie.txt](https://github.com/minukodu/ioBroker.minuvis/files/8986094/iPad_V2.-.Kopie.txt)



Gruß Michael

**Comment by MMeinhardt1** [comment]
Hi Sepp @SVallant,

der Import hat jetzt nach ein paar Versuchen nun doch funktioniert, es lag an einem "timestamp" Widget auf meiner Statuspage.
Jetzt kann ich mich mal mit V2 auseinandersetzen.

Gruß Michael
